 network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: no
      addresses:
        - 192.168.29.5/24
      routes:
        - to: default
          via: 192.168.29.1
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
